#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Writes mesa_android_gl_forward.inc: every GLES 3.2 entry point of
mesa_android_gl.c, forwarding to Mesa's libGLESv2 in its own namespace.

usage: gen_mesa_gl.py /usr/include/GLES3/gl32.h > mesa_android_gl_forward.inc"""
import re
import sys

proto = re.compile(r"^GL_APICALL (.+?)\s*GL_APIENTRY (gl\w+) \((.*)\);$")
out = ["/* Generated by gen_mesa_gl.py - do not edit. */", "#include <GLES3/gl32.h>"]
for line in open(sys.argv[1]):
    m = proto.match(line.strip())
    if not m:
        continue
    ret, name, params = m.groups()
    args = [] if params.strip() == "void" else [re.findall(r"\w+", p)[-1] for p in params.split(",")]
    ret_kw = "" if ret == "void" else "return "
    out.append(f"API {ret} GL_APIENTRY {name}({params})\n{{\n"
               f"    static {ret} (GL_APIENTRY *p)({params});\n"
               f"    if (!p)\n        *(void **)&p = mesa_android_gl_sym(\"{name}\");\n"
               f"    {ret_kw}p({', '.join(args)});\n}}")
print("\n".join(out))
