#!/usr/bin/env python3
"""Generates gles_forward.c: every GLES 3.2 entry point (same set glvnd's
libGLESv2.so.2 exports), forwarding to Android's /system/lib64/libGLESv2.so.
Functions listed in OVERRIDDEN are implemented by hand in gles.c.

usage: gen_gles.py <NDK sysroot>/usr/include/GLES3/gl32.h > gles_forward.c"""
import re
import sys

OVERRIDDEN = {"glShaderSource", "glGetString", "glGetStringi", "glGetIntegerv",
              "glTexImage2D", "glTexSubImage2D", "glTexImage3D", "glTexSubImage3D"}
proto = re.compile(r"^GL_APICALL (.+?)\s*GL_APIENTRY (gl\w+) \((.*)\);$")

funcs = []
for line in open(sys.argv[1]):
    m = proto.match(line.strip())
    if m:
        funcs.append(m.groups())

out = ['/* Generated by gen_gles.py from the NDK\'s GLES3/gl32.h - do not edit. */',
       '#include <GLES3/gl32.h>', '#include "gles_internal.h"', '',
       '#pragma GCC visibility push(default)', '']
table = []
for ret, name, params in funcs:
    if name in OVERRIDDEN:
        continue
    args = [] if params.strip() == "void" else [re.findall(r"\w+", p)[-1] for p in params.split(",")]
    ret_kw = "" if ret == "void" else "return "
    out.append(f"static {ret} (GL_APIENTRY *p_{name})({params});")
    out.append(f"GL_APICALL {ret} GL_APIENTRY {name}({params})\n{{\n    CHAM_NOTE_CALL(\"{name}\");\n    {ret_kw}p_{name}({', '.join(args)});\n}}\n")
    table.append(f'    {{"{name}", (void **)&p_{name}}},')
out += ['#pragma GCC visibility pop', '',
        'const struct cham_gl_entry cham_gl_entries[] = {'] + table + ['    {0, 0},', '};', '']
print("\n".join(out))
